import json

# Read source
with open('/tmp/re9-translate/json/natives/stm/message/gui/gui_common.msg.23.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

translations = {}

for entry in data['entries']:
    name = entry['name']
    en = entry.get('strings', {}).get('en', '')
    translations[name] = en  # default to English, we'll override below

# Now define all Czech translations
cz = {
    "Com_Yes": "Ano",
    "Com_No": "Ne",
    "Com_Ok": "OK",
    "Com_R_L": "Zrusit",
    "Com_R_D": "Potvrdit",
    "Com_Next": "Dalsi",
    "Com_Rturn": "Zpet",
    "Com_Close": "Zavrit",
    "Com_Craft": "Vyrobit",
    "Com_Auto_Organize": "Automaticke razeni",
    "Com_Hold": "DRZET",
    "Com_Push": "STISKNOUT",
    "Com_FULL": "PLNO",
    "Com_Hold_Skip": "Preskocit (drzet)",
    "Com_Go_Up": "Vyslapat nahoru",
    "Com_Climb_Over": "Preskocit",
    "Com_Martial_Arts_Kick": "Utok zblizka",
    "Com_Escape": "Vymanit se",
    "Com_Analyze": "Analyzovat",
    "Com_Hold_In_Hand": "Drzet",
    "Com_Carry": "Nest",
    "Com_Carrying": "Neseni",
    "Com_Pick_Up": "Vzit",
    "Com_Saving": "Ulozit",
    "Com_Temporarily_Suspend": "Pauza",
    "Com_Throwing": "Hodit",
    "Com_Hide": "Schovat se",
    "Com_Enter": "Vstoupit",
    "Com_Read": "Precist",
    "Com_Swing_Around": "Hmitat",
    "Com_Swing_Around1": "Hmitat",
    "Com_Throwing1": "Hodit",
    "Com_Put_Down": "Polozit Emily",
    "Com_Hold_Arms": "Zvednout Emily",
    "Com_Take_Off": "Uvolnit se",
    "Com_Repair": "Opravit",
    "Com_View_Map": "Mapa",
    "Com_Combine": "Zkombinovat",
    "Com_Skip_Talk": "Preskocit rozhovor",
    "Com_Take_Down": "Srazit k zemi",
    "Com_Recipes_Crafts": "Recepty na vyrobe",
    "Com_Power_Off": "Vypnout",
    "Com_Pass_Under": "Podlezt",
    "Com_Search": "Prozkoumat",
    "Com_Reset_Ability": "",
    "Com_Generate": "",
    "Com_Interact": "<ICON INTERACT>",
    "Com_Cancel": "<ICON CANCEL>",
    "Com_Tab_Left": "<ICON TAB_LEFT>",
    "Com_Tab_Right": "<ICON TAB_RIGHT>",
    "Com_Area_Left": "<ICON AREA_LEFT>",
    "Com_Area_Right": "<ICON AREA_RIGHT>",
    "Com_Floor_Up": "<ICON FLOOR_UP>",
    "Com_Floor_Down": "<ICON FLOOR_DOWN>",
    "Com_Cursor_Up": "<ICON CURSOR_UP>",
    "Com_Cursor_Down": "<ICON CURSOR_DOWN>",
    "Com_Cursor_Left": "<ICON CURSOR_LEFT>",
    "Com_Cursor_Right": "<ICON CURSOR_RIGHT>",
    "Com_Equip_Up": "<ICON EQUIP_UP>",
    "Com_Equip_Down": "<ICON EQUIP_SHORTCUT_1>",
    "Com_Equip_Left": "<ICON EQUIP_SHORTCUT_2>",
    "Com_Equip_Right": "<ICON EQUIP_SHORTCUT_3>",
    "Com_Equip_Down2": "<ICON EQUIP_SHORTCUT_4>",
    "Com_Equip_Left2": "<ICON EQUIP_SHORTCUT_5>",
    "Com_Equip_Right2": "<ICON EQUIP_SHORTCUT_6>",
    "Com_Grapple_Counter": "<ICON GRAPPLE_COUNTER>",
    "Com_Skip": "<ICON EVENT_SKIP>",
    "Com_Link": "<ICON LINK>",
    "Com_Counter_Ampoule": "<ICON DECIDE>",
    "Com_Item_ShortCut_U": "<ICON INVENTORY>",
    "Com_Item_ShortCut_D": "<ICON DECIDE>",
    "Com_Item_ShortCut_L": "<ICON DEFAULT> ",
    "Com_Item_ShortCut_R": "<ICON CANCEL>",
    "Com_Sort": "<ICON SORT>",
    "Com_Item_Rotation_L": "<ICON TAB_LEFT>",
    "Com_Item_Rotation_R": "<ICON TAB_RIGHT>",
    "Com_Powerup_Shortcut": "<ICON POWERUP_SHORTCUT>",
    "Com_Map_Area_Left": "<ICON MAPAREA_LEFT>",
    "Com_Map_Area_Right": "<ICON MAPAREA_RIGHT>",
    "Com_All_Reset": "<ICON OPTION_RESET>",
    "Com_Option_Stick_L": "<ICON LS_FIX>",
    "Com_Option_Stick_R": "<ICON RS_FIX>",
    "Com_Guide_Decide": "<ICON DECIDE> Potvrdit",
    "Com_Guide_OK": "<ICON DECIDE> OK",
    "Com_Guide_Detail": "<ICON DECIDE> Podrobnosti",
    "Com_Guide_Search": "<ICON INTERACT> Prozkoumat",
    "Com_Guide_Rturn": "<ICON CANCEL> Zpet",
    "Com_Guide_Rturn_Action": "<ICON CANCEL_ACTION> Zpet",
    "Com_Guide_Rturn_Map": "<ICON SCALE_UP> Zpet",
    "Com_Guide_Close": "<ICON CANCEL> Zavrit",
    "Com_Guide_Close_Action": "<ICON CANCEL_ACTION> Zavrit",
    "Com_Guide_Close_Inventory": "<ICON INVENTORY> Zavrit",
    "Com_Guide_Cancel": "<ICON CANCEL> Zrusit",
    "Com_Guide_Next": "<ICON DECIDE> Dalsi",
    "Com_Guide_Skip": "<ICON DECIDE> Preskocit",
    "Com_Guide_Pause_Skip": "<ICON USE_HOLD> Preskocit (drzet)",
    "Com_Guide_Page_Skip": "<ICON PAGE_UDRS> Rychle posouvani",
    "Com_Guide_Rotation0": "<ICON CAMERA> Otocit",
    "Com_Guide_Rotation1": "<ICON ROTATE> / <ICON TAB_LEFT><ICON TAB_RIGHT> Otocit",
    "Com_Guide_Scaling0": "<ICON SCALE_DOWN> / <ICON SCALE_UP> Oddalit/Priblizit",
    "Com_Guide_Scaling1": "<ICON SCALE_UP> / <ICON SCALE_DOWN> Priblizit/Oddalit",
    "Com_Guide_Trans": "<ICON TRANSLATION> Presunout pozici",
    "Com_Guide_Move_Item": "<ICON DEFAULT> Presunout",
    "Com_Guide_Move": "<ICON CURSOR> Presunout",
    "Com_Guide_Reset_Map": "<ICON DEFAULT> Aktualni poloha",
    "Com_Guide_Page_Change": "<ICON CURSOR_LRPV> Zmenit stranku",
    "Com_Guide_File_Next": "<ICON DECIDE> Dalsi",
    "Com_Guide_Sort": "<ICON SORT> Seradit",
    "Com_Guide_Category_Sort": "<ICON SORT> Seradit:",
    "Com_Guide_Area_Change": "<ICON AREA_LRPV> Zmenit oblast",
    "Com_Guide_Floor_Change": "<ICON FLOOR_UDPV> Zmenit patro",
    "Com_Guide_Reset_Search": "<ICON DEFAULT> Resetovat",
    "Com_Guide_Hold_Skip_Pause_Menu": "Preskocit (drzet) <ICON PAUSE> Pauza",
    "Com_Guide_Hold_Skip_Pause": "Preskocit <ICON PAUSE> Pauza",
    "Com_Guide_KeyVisualViewer": "<ICON EVENT_SKIP> Preskocit <ICON PAUSE> Menu pauzy",
    "Com_Guide_All_Reset": "<ICON OPTION_RESET> Resetovat vse",
    "Com_Guide_Category_Reset": "<ICON DEFAULT> Resetovat kategorii",
    "Com_Guide_Sub_Category_Reset": "<ICON DEFAULT> Resetovat podkategorii",
    "Com_Guide_Select_UD": "<ICON CURSOR_UDPV> Vybrat",
    "Com_Guide_Select_LR": "<ICON CURSOR_LRPV> Zmenit hodnotu",
    "Com_Guide_Default": "<ICON DEFAULT> Resetovat",
    "Com_Guide_Submenu": "<ICON INVENTORY> Podmenu",
    "Com_Guide_Switch": "<ICON AREA_LEFT> / <ICON AREA_RIGHT> Prepnout",
    "Com_Guide_SendTo": "<ICON DECIDE> Ulozit",
    "Com_Guide_Take_Out": "<ICON DECIDE> Vyjmout",
    "Com_Guide_SendTo1": "<ICON OPTION_RESET> Ulozit",
    "Com_Guide_Take_Out1": "<ICON OPTION_RESET> Vyjmout",
    "Com_Guide_Number_Change": "<ICON CURSOR_LRPV> Zmenit mnozstvi",
    "Com_Guide_Confirm": "<ICON DECIDE> Potvrdit",
    "Zoom": "<ICON SCOPE> ZOOM: {0}",
    "Zoom1": "<ICON SCOPE> Priblizit",
    "Zoom2": "<ICON SCOPE> Priblizit vice",
    "Zoom3": "<ICON SCOPE> Oddalit",
    "Com_Guide_Auto_Organize": "<ICON SORT> Automaticke razeni",
    "Com_Guide_HOLD_Auto_Organize": "<ICON SORT> Automaticke razeni (drzet)",
    "Com_Guide_Map_Open": "<ICON SUBMENU> Otevrit mapu",
    "Com_Guide_Look": "<ICON CAMERA> Rozhlednout se",
    "Com_Guide_Notice": "<ICON INTERACT> Proverit",
    "Com_Guide_Config_Cancel": "<ICON CANCEL_ASSIGN><COLOR preset=\"TextColor1\">Zrusit</COLOR>",
    "Com_Guide_Config_Blank": "<ICON DELETE_ASSIGN><COLOR preset=\"TextColor1\">Zrusit prirazeni tlacitka</COLOR>",
    "Com_Guide_Sharpen": "<ICON SHARPEN> Nabrousit",
    "Com_Guide_Transfer_ItemSlot": "<ICON AREA_LEFT> / <ICON AREA_RIGHT> Presunout slot predmetu",
    "Com_Guide_PlayStop": "<ICON DECIDE> Pozastavit / Prehrat",
    "Com_Guide_ChangeGameMode": "<ICON OPTION_RESET> Zmenit herni rezim",
    "Com_Guide_Attach_Charm": "<ICON DECIDE> Pripnout privesek",
    "Com_Guide_Remove_Charm": "<ICON DECIDE> Sundat privesek",
    "Com_Guide_Attach_Sight_Scope": "<ICON DECIDE> Nasadit",
    "Com_Guide_Remove_Sight_Scope": "<ICON DECIDE> Sundat",
    "Com_Guide_Reset_Ability": "<ICON DEFAULT> ",
    "Com_Guide_Generate": "<ICON DECIDE> Rafinovat (drzet)",
    "Com_Guide_Inventory_Confirm": "<ICON OPTION_RESET> Zkontrolovat inventar",
    "Com_Guide_PageScroll": "<ICON SCROLL_UDRS>Posouvat",
    "Com_Guide_Gm_Cancel": "<ICON CANCEL> Zrusit",
    "Com_Guide_Gm_Cancel_Action": "<ICON CANCEL_ACTION> Zrusit",
    "Com_Guide_Gm_Move_Pencil0": "<ICON PENCIL> Pohnout tuzkou",
    "Com_Guide_Gm_Black_Out0": "<ICON PENCIL2> Vybarvit",
    "Com_Guide_Gm_Black_Out1": "<ICON TP_DRAG> Vybarvit",
    "Com_Guide_Gm_Rotation0": "<ICON CURSOR_LRLS> Otocit",
    "Com_Guide_Gm_Select0": "Vybrat cifernik",
    "Com_Guide_Gm_Rotation1": "Otocit",
    "Com_Guide_Gm_Check0": "<ICON DECIDE> Zkontrolovat",
    "Com_Guide_Gm_Hide": "{0} Schovat se",
    "Com_Guide_Gm_Peek": "{0} Vykuknout",
    "Com_Guide_Gm_Go_Out": "{0} Vyjit ven",
    "Com_Guide_Gm_Turn_Page": "<ICON MOVE_LR>Otocit stranku",
    "Com_Guide_Gm_Look": "<ICON CAMERA> Rozhlednout se",
    "Com_Guide_Gm_PlugIn": "Zasunout",
    "Com_Guide_Gm_Remove0": "Vyjmout",
    "Com_Guide_Gm_Select1": "<ICON CURSOR_LRLS> Vybrat tlacitko",
    "Com_Guide_Gm_Select2": "<ICON CURSOR_LRLS> Vybrat prepinac",
    "Com_Guide_Gm_Switching": "<ICON SWITCH_UDRS> Prepnout prepinac",
    "Com_Guide_Gm_Twist": "<ICON SWITCH_UDRS> Otocit",
    "Com_Guide_Gm_Operate_Lever": "<ICON SWITCH_UDRS> Pohnout",
    "Com_Guide_Gm_Move_Cursor0": "<ICON PENCIL> Pohnout kurzorem",
    "Com_Guide_Gm_Rotation3": "<ICON ROTATE_R> Otocit",
    "Com_Guide_Gm_Convert0": "<ICON DECIDE> Prevest",
    "Com_Guide_Gm_Zoom0": "<ICON SCALE_DOWN> / <ICON SCALE_UP> Priblizeni",
    "Com_Guide_Gm_Rotation4": "<ICON ROTATE_LRRS> Otocit",
    "Com_Guide_Gm_Remove1": "<ICON DECIDE> Otevrit",
    "Com_Guide_Gm_Rotation5": "<ICON ROTATE_LRRS> Rozebrat",
    "Com_Guide_Gm_Slide_Switch0": "<ICON CURSOR_LRLS> Zmenit posuvnik",
    "Com_Guide_Gm_Draw_Out": "Vytahnout",
    "Com_Guide_Gm_Draw_Out2": "Vytahnout",
    "Com_Guide_Gm_Unlock": "<ICON DECIDE> Odemknout",
    "Com_Guide_Gm_Mortar0": "<ICON CAMERA> Pohnout",
    "Com_Guide_Gm_Mortar1": "<ICON ATTACK> Vystrelit",
    "Com_Guide_Gm_Go_Outside": "<ICON DECIDE> Vyplazit se ven",
    "Com_Guide_Gm_Go_Outside_Action": "<ICON INTERACT> Vyplazit se ven",
    "Com_Guide_Gm_Moving": "<ICON MOVE> Plazit se",
    "Com_Guide_Gm_Fit_Key": "Pouzit klic",
    "Com_Guide_Gm_Stick_In": "Zasunout",
    "Com_Guide_Gm_Fill_Up": "Naplnit",
    "Com_Guide_Gm_Refuel": "Natankovat",
    "Com_Guide_Gm_Go_Down": "Sestoupit",
    "Com_Guide_Gm_Go_Down1": "Sestoupit",
    "Com_Guide_Gm_Go_Down2": "Slanit",
    "Com_Guide_Gm_Go_Down3": "Seskocit",
    "Com_Guide_Gm_Activation": "Aktivovat",
    "Com_Guide_Gm_Push_Up": "Zvednout",
    "Com_Guide_Gm_Destroy_Item": "<ICON DESTROY_LEFT> Znicit Elpis",
    "Com_Guide_Gm_Refine_Item": "<ICON REFINE_RIGHT> Uvolnit Elpis",
    "Com_Guide_Gm_Decide": "<ICON BLANK> Potvrdit",
    "Com_Guide_Gm_Cancel1": "<ICON CANCEL> Zrusit",
    "Com_Guide_Gm_Reset": "<ICON DEFAULT> Resetovat",
    "Com_Guide_Gm_Select3": "<ICON CURSOR_LRLS> Vybrat cifernik",
    "Com_Guide_Gm_Panel_Switch0": "<ICON DECIDE> Prepnout zobrazeni",
    "Com_Guide_Gm_Detonate": "Odpalit",
    "Com_Guide_Input0": "Destrukce\r\n(Nespravne heslo)",
    "Com_Guide_Input1": "Requiem\r\n(Spravne heslo)",
    "Com_Guide_Input2": "Destrukce\r\n(Znicit Elpis)",
    "Com_Guide_Input3": "Requiem\r\n(Rafinovat Elpis)",
    "Com_Guide_Recovery_Dying_State": "{0} Leciva polozka",
    "Com_Guide_Climb_Over": "{0} Preskocit",
    "Com_Guide_Go_Up_FPS": "{2}Vyslapat nahoru",
    "Com_Guide_Go_Down_FPS": "{3}Seskocit",
    "Com_Guide_Go_Up": "{0} Vyslapat nahoru",
    "Com_Guide_Long_Jump": "{0} Skocit",
    "Com_Guide_Bike_Operate": "<ICON ATTACK> Zrychlit\r\n<ICON HOLD> Brzdit\r\n<ICON MOVE> Ridit",
    "Com_Guide_Bike_Battle": "<ICON HOLD> + <ICON ATTACK> Strelit\r\n<ICON CAMERA> Zamirit\r\n<ICON RELOAD> Prebit",
    "Com_Guide_Bike_Unit": "KM/H",
    "Figures_Change_Model": "<ICON TAB_LEFT><ICON TAB_RIGHT> Zmenit model",
    "Figures_Rotate": "<ICON ROTATE> Otocit",
    "Artwork_Change_Concept_Art": "<ICON TAB_LEFT><ICON TAB_RIGHT> Zmenit grafiku",
    "Figures_Artwork_Toggle_UI": "<ICON DISPLAY> Skryt/Zobrazit ovladani",
    "Com_Copyright": "\u00a9CAPCOM",
    "Com_Log_Update_Map": "Mapa aktualizovana",
    "Com_Log_Add_File": "Ziskan dokument",
    "Com_Log_Size_Up": "Vylepseni kufru (8x13)",
    "Com_Log_Get_Item00": "{0} x{1}",
    "Com_Log_Add_World_Map": "Mapa sveta aktualizovana",
    "Com_Log_Add_Craft_Recipe": "Pridano do vyrobe:",
    "Com_Log_Add_Icon": "Ikona pridana na mapu",
    "Com_Log_Add_Unlocked_Achievement": "{0}",
    "Com_Log_Time_Bonus": "",
    "Com_Condition_Type0": "V PORADKU",
    "Com_Condition_Type1": "POZOR",
    "Com_Condition_Type2": "NEBEZPECI",
    "Com_Ability_Status0": "Nezranitelnost",
    "Com_Ability_Status1": "Nekonecna munice/odolnost",
    "Com_Craft_Count": "Vyrobeno: x {0}",
    "Com_Sale_Price_Currency": "Hodnota: {0} kreditu",
    "Com_Subtitle0": "<COLOR preset=\"{0}\">{1}:</COLOR> {2}",
    "Com_Subtitle1": "{0}",
    "Com_Unopened": "???",
    "Com_Unopened1": "???",
    "Com_Item_Count": "{0} ({1})",
    "Com_Item_Percent_Scan": "{0} (+{1}%)",
    "Com_Button_Layout_2": "{0} + {1}",
    "Com_Nothing": " ",
    "Com_Plus": "+",
    "Com_Plus_Count": "+ {0}",
    "Com_Hyphen": "-",
    "Com_Percent": "{0}%",
    "Com_Percent_Scan": "{0}<SIZE 36>%</SIZE>",
    "Com_Angle": "{0}\u00b0",
    "Com_Slash": "/",
    "Com_Infinity": "\u221e",
    "Com_Equip": "E",
    "Com_Cross": "x{0}",
    "Com_Multi_Count": "x {0}",
    "Com_Multi": "x",
    "Com_Multi_Num": "{0} \u00d7 {1}",
    "Com_Rate": "{0} / {1}",
    "Com_Lv": "Ur. {0}",
    "Com_Date_Full": "{1:D2}/{2:D2}/{0:D4}\r\n{3:D2}:{4:D2}:{5:D2}",
    "Com_Date00": "{1:D2}/{2:D2}/{0:D4}",
    "Com_Time00": "{3:D2}:{4:D2}:{5:D2}",
    "Com_Time01": "{0}:{1:D2}",
    "Com_Time02": "{0}:{1:D2}.<SIZE 36>{2:D2}</SIZE>",
    "Com_PlayTime": "{0}:{1:D2}:{2:D2}",
    "Com_AddTime": "+{0}.<SIZE 36>{1:D2}</SIZE>",
    "Com_Currency": "Kredity",
    "Com_Currency_Num": "<ICON CURRENCY>{0}",
    "Com_Point": "{0} b.",
    "Com_Sale_Price": "Prodejni cena",
    "Gm_no_signal": "BEZ SIGNALU",
    "Gm_Mortality_Rate": "",
    "Com_Arrow_L": "\u2190",
    "Com_Arrow_R": "\u2192",
}

# Apply Czech translations
for key, val in cz.items():
    translations[key] = val

# Verify all entries are present
assert len(translations) == len(data['entries']), f"Mismatch: {len(translations)} vs {len(data['entries'])}"

# Write output
outpath = '/tmp/re9-translate/translations/natives/stm/message/gui/gui_common.msg.23.json'
with open(outpath, 'w', encoding='utf-8') as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)

print(f"Written {len(translations)} entries to {outpath}")
